### PR TITLE
Target: Loading Zites

### PR DESCRIPTION
**Pull request by mkg20001**
Final goals of this pr:
 - [x] Downloading Zites
 - [x] Verifying contents and files ~~recursively~~
 - ~~(maybe) multi-user rules and downloading~~ (pr is already way too big)

### CODE REVIEW

**Comment by mkg20001** [comment]
Currently working on the streams and trees. Will take a bit until it loads in the browser

**Comment by Plasmmer** [comment]
@mkg20001
Some goal is already done?

**Comment by mkg20001** [comment]
It downloads the content json. Which is a part of the first goal.
So almost one goal done

**Comment by mkg20001** [comment]
Now the tree is almost done. Maybe I can get downloading to work in a few days

**Comment by mkg20001** [comment]
It's merge time

**Pull request merged**
