### PR TITLE
Feature: TLS

### PR DESCRIPTION
**Pull request by mkg20001**
Goals:
 - [ ] Working tls handshakes
 - [ ] TLS RSA encryption
 - [ ] TLS ECC encryption

### CODE REVIEW

**Comment by mkg20001** [comment]
Currently it just times out without sending anything
screenshot

**Comment by mkg20001** [comment]
Found the possible cause of the timeout: The net.socket is never connected. Seems like .pipe doesn't connect it.

**Comment by mkg20001** [comment]
Now I'm getting `Error: 139640545445696:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:`

**Comment by Plasmmer** [comment]
Reference: #54.

**Comment by Plasmmer** [comment]
Reference: https://github.com/ZeroNetJS/zeronet-js/issues/1.

**Comment by mkg20001** [comment]
So far TLS works, but interop fails.

**Comment by mkg20001** [comment]
Closing in favor of #88

**Pull request closed without merging**
